"""
Publisher module — creates GitHub PRs in the target site repo.

Flow:
  1. Create a new branch in the local site repo clone
  2. Write the content file to the configured content path
  3. Commit and push the branch
  4. Open a PR via `gh` CLI
"""

import logging
import os
import subprocess
from datetime import datetime
from typing import List, Optional

import pytz

log = logging.getLogger(__name__)


def _run(cmd: List[str], cwd: str = None) -> subprocess.CompletedProcess:
    """Run a subprocess command and return the result."""
    log.debug("Running: %s", " ".join(cmd))
    result = subprocess.run(cmd, capture_output=True, text=True, cwd=cwd)
    if result.returncode != 0:
        log.error("Command failed: %s\nstderr: %s", " ".join(cmd), result.stderr)
    return result


def create_pr(draft: dict, config: dict, repo_path: str, dry_run: bool = False) -> Optional[str]:
    """
    Create a GitHub PR with the content draft.

    Args:
        draft: Output from drafter.draft_take()
        config: Pipeline config dict
        repo_path: Absolute path to the site repo
        dry_run: If True, write the file but don't push or create PR

    Returns:
        PR URL on success, None on failure
    """
    publishing = config.get("publishing", {})
    site = config.get("site", {})
    tz = pytz.timezone(config.get("pipeline", {}).get("timezone", "UTC"))

    content_path = site.get("content_path", "src/content/pov")
    base_branch = publishing.get("base_branch", "main")
    branch_prefix = publishing.get("branch_prefix", "pov")

    content_dir = os.path.join(repo_path, content_path)
    if not os.path.isdir(content_dir):
        log.error("Content directory does not exist: %s", content_dir)
        return None

    today = datetime.now(tz).strftime("%Y-%m-%d")
    branch_name = f"{branch_prefix}/{today}-{draft['slug']}"
    file_path = os.path.join(content_dir, draft["filename"])
    relative_path = os.path.join(content_path, draft["filename"])

    # Ensure we're on base branch and up to date
    result = _run(["git", "checkout", base_branch], cwd=repo_path)
    if result.returncode != 0:
        log.error("Failed to checkout %s", base_branch)
        return None

    _run(["git", "pull", "origin", base_branch], cwd=repo_path)

    # Create and checkout new branch
    result = _run(["git", "checkout", "-b", branch_name], cwd=repo_path)
    if result.returncode != 0:
        log.error("Failed to create branch %s", branch_name)
        result = _run(["git", "checkout", branch_name], cwd=repo_path)
        if result.returncode != 0:
            return None

    # Write content file
    with open(file_path, "w") as f:
        f.write(draft["content"])
    log.info("Wrote content file: %s", file_path)

    if dry_run:
        log.info("[DRY RUN] Would create PR for: %s", draft["metadata"]["title"])
        os.remove(file_path)
        _run(["git", "checkout", base_branch], cwd=repo_path)
        _run(["git", "branch", "-D", branch_name], cwd=repo_path)
        return "DRY_RUN"

    # Stage and commit
    _run(["git", "add", relative_path], cwd=repo_path)

    commit_msg = f"Add POV take: {draft['metadata']['title']}"
    result = _run(["git", "commit", "-m", commit_msg], cwd=repo_path)
    if result.returncode != 0:
        log.error("Failed to commit")
        _run(["git", "checkout", base_branch], cwd=repo_path)
        return None

    # Push branch
    result = _run(["git", "push", "-u", "origin", branch_name], cwd=repo_path)
    if result.returncode != 0:
        log.error("Failed to push branch %s", branch_name)
        _run(["git", "checkout", base_branch], cwd=repo_path)
        return None

    # Create PR via gh CLI
    meta = draft["metadata"]
    pr_body = f"""## POV Take: {meta['title']}

**Theme:** {meta['theme']}
**Source:** [{meta['title']}]({meta['source_url']})
**Tags:** {', '.join(meta['tags'])}

---

### Social Draft
```
{draft.get('linkedin_draft', 'No social draft generated.')}
```

---

*Auto-generated by pov-pipeline. Review, edit if needed, and merge to publish.*"""

    result = _run([
        "gh", "pr", "create",
        "--title", f"POV: {meta['title'][:65]}",
        "--body", pr_body,
        "--base", base_branch,
        "--head", branch_name,
    ], cwd=repo_path)

    # Switch back to base branch
    _run(["git", "checkout", base_branch], cwd=repo_path)

    if result.returncode == 0:
        pr_url = result.stdout.strip()
        log.info("Created PR: %s", pr_url)
        return pr_url
    else:
        log.error("Failed to create PR: %s", result.stderr)
        return None
